global:
  resolve_timeout: 5m

templates:
  - 'template/wechat.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  wechat_configs:
  - send_resolved: true
    to_party: '6'
    agent_id: '1000009'
    corp_id: 'ww9f6f96516581acc0'
    api_secret: '3OKWOzmSBFDXIkqXe2IodwUevCMjK1_P8lnobflgkNM'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['dev', 'instance']
