apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: demo-grafana-prd.wzx.cn
    http:
      paths:
      - backend:
          serviceName: ack-prometheus-operator-grafana
          servicePort: 80
