apiVersion: v1
kind: Secret
metadata:
  name: jenkins-auth-config
  namespace: jx
data:
  id_rsa.pub: |
    c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFET1VzWmZLc2JTVEN5cFkrUTRq
    U1VFMnV0a2l2KzFEMFM1QldPcUtUWUNEbFd0OEFJbEc4YlBLYjRQdDkxNHlmOTJuOU9YQitMNUJL
    N2VQZ21IQ3krWTRjOG51dnFpUnlPMGV1RlJCNDdlWmlWY0pIaWc4ejFkU0xIclBSSXdnSVNsWFFH
    ZjZJeUZvdEdvNFROS05GQSsyM1k5SHFya0Z5cWtYeVBTWWxJV0FxOGZDVEwvdlZyd3EvS29HN0pw
    ZUJIUmc2WjM3bTJ2SXhHcUZjUG1FekVLM1hKdDZZL3NIalMrRE9mdmI1TVIzMWUzNDNUZWh6TlNM
    b3ZXdWd2MkVmbnlHSmhLK3BmTlhlMHpmQnZxZk9jUnAyazV2eWJxb1R0WUhIMjRNRWNRVmR3anJB
    REJuRHRlbXVwak9tNEZPTVZLdW1HaUFtaXJvUFliVmVDUEJWVTMgcm9vdEBpWjh2YmEzMzgxaXRu
    cnV5YTlyZXZsWgo=
  id_rsa: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBemxMR1h5ckcw
    a3dzcVdQa09JMGxCTnJyWklyL3RROUV1UVZqcWlrMkFnNVZyZkFDCkpSdkd6eW0rRDdmZGVNbi9k
    cC9UbHdmaStRU3UzajRKaHdzdm1PSFBKN3I2b2tjanRIcmhVUWVPM21ZbFhDUjQKb1BNOVhVaXg2
    ejBTTUlDRXBWMEJuK2lNaGFMUnFPRXpTalJRUHR0MlBSNnE1QmNxcEY4ajBtSlNGZ0t2SHdreQov
    NzFhOEt2eXFCdXlhWGdSMFlPbWQrNXRyeU1ScWhYRDVoTXhDdDF5YmVtUDdCNDB2Z3puNzIrVEVk
    OVh0K04wCjNvY3pVaTZMMXJvTDloSDU4aGlZU3ZxWHpWM3RNM3diNm56bkVhZHBPYjhtNnFFN1dC
    eDl1REJIRUZYY0k2d0EKd1p3N1hwcnFZenB1QlRqRlNycGhvZ0pvcTZEMkcxWGdqd1ZWTndJREFR
    QUJBb0lCQURzNkhjSGg2TE1qdE1wbgpaM01vYVZFTWV2Z2d3cWk2R2xNMmpkYWgvK1AxTTNrNzVa
    RzdlSVd0aU9iQU5DNWhaaGtxWmpYN3lKY05WaGxzCkc1WU5pdnRMRHdscnJsajVMUEc1T0libk1Z
    YjhNWXRTMk9IekVWRis5YnYraXdNclVXaWEyMFdKSHhXWm1LL3UKL2FjMmZ6YWNEMFFhVXBvcFlF
    OVJGRnBuYVFMeC9DK3VTYkNaanZCcEVjMTBVTmprZWVubEY0ZE5FV0hrV3hmTApUSk81ZnoxNzUv
    V2NwUThzbm8wZW1vVzFIa3BiSTdQbUZpNktRc2JKczdybk1OaHFvVDJZVytRM0Vic3oxRUVICnZx
    M052ZGtucWc4T0liME1tVHBOOEsvMS93WDJPUzVUQ0ovNDVGd2VhRDcrSUQxK2tPUUVkVUptMjc2
    MjNtYU4KWFhDdUZva0NnWUVBOGJqejZZbWsyOGtlblRaVmhXeHQwNFprekFEWHhGZUdyY0pIUTk4
    YVY0QjFSVGF0U0lPVwpHVWU0OTMzTkVCYXJoRkJsdWQvUzZ6UXBZR0tXWTlsR05YazVlNElQT3E4
    VVRBMEpJRjlVT2JDd0pKb1BZZ1pvCnlTRkFYMS9TQk5SREtISmtRcjJoYnBmZzM5V0hCN212VHIv
    ejJpU0ZaMXE2Q2FtNUtiT2J5b1VDZ1lFQTJvS08KczkvV1NkQW1lSTc4OFRpUnBFY0dTUzlhekpL
    b2Eyb3ord29yT2NLbExHdGluYlhUeUc2ZnRoY1lPeXJkTXUzZQpnYlpEejN3eEpIcDBUSDl1V3hy
    NGlkZVB6SUdyaERWdVg2STdUNUcrQVJ0THFTU2laQ2l4S00rUHczQ0RjR1U1CmNQdVhJaHdGdkVO
    ejNNdVowRzBRdWxFSDEzT0M3dTJpbDhiVWs0c0NnWUI5elVCRVB2cXAyRll5ZytDbWUvUDgKcm1r
    dk14RVlnbVQ1Y2E4ZFI3T3g3bzBaNUlieXdta1A1eUFBemx3M0QxVmNtMnNWL2NNTDNpM2FsL1Ns
    S3FNNwptVWV0VzljSk42MWNsencwdU9oZ3pmQWVYSCs5Q0pEb2ZJSEFJV0p3V1BoS3lKNGRqZ3ZD
    UHhFdDdUZEZjZ0ltCi9nZXZkR3BwaS9KZXJSSk0vY2tLOFFLQmdRREdaZjZPQWJIK3lUajFBOWRV
    YW1tS3dGWkx3dXh0ak1mUTU5Z1UKbXZJT2V0WWdVOHh4cC9PSUxERmxVdWpVYUNINXFSTDdzWE0y
    Zyt2VzFEeWViS0hWcE5KL3piS3FIQjZRWnpjMQpMQWN3UXdOQzIvYkJ1QnFlV0hncXR2TXdvQXNu
    MVREbmpmaDJwdnpxS0ZDZDdGdFhiSC9ndTh3ajZxUzZyaGVRCk9aOHY2d0tCZ1FEb1lSSitJcW1L
    YWJDSC96Q2g0elFMZm4rS3pLQ09kdjZQbXErbGpoNUdEWEZqSkJJbHdOYVoKYXNCdEpXQW5SdS85
    M2pwSHQ1ZkFONEpjbGJQeUVNSTV5MzI1MVhzYk4vaHpYeGRZVjNNOWJGay9MR2Z3QjNYMwpocmdE
    SEdrT05sQUFnbmdHcllDZDBTT09aZ1BaSGN5SXlsSUpBRERBZkdiUkc3QVpycXZ2MEE9PQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  known_hosts: |
    Z2l0LnF1dG91dGlhby5uZXQsMTcyLjE2LjEyMi4xNTAgZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFB
    RTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQk5RdTZMVkRy
    bVZmc29mZDNZV3BSRklzaDhRdlJtMnZKZDFUNkplRS9KbUx3b2N6KzhhbjU4dlRMR3R4V2E0Vk55
    ZWJ1OEJBa2lXTlNnc3kvR0RVTmhRPQo=

