apiVersion: v1
kind: Ingress
metadata:
    name: wordpress_ingress
    namespace: default
spec:
  rules:
  - http:
    paths:
        - path: /
            backend:
              serviceName: wordpress-test-wordpress
              servicePort: 80
