groups:
 - name: steps-rules
   rules:
   - alert: 日活抖动 # 告警名称
     expr: (abs(steps_activity_today{group="business_group",instance="39.105.157.120:8981",job="business",type="uid"} - steps_activity_today{group="business_group",instance="39.105.157.120:8981",job="business",type="uid"} offset 1d) * 100 / steps_activity_today{group="business_group",instance="39.105.157.120:8981",job="business",type="uid"} offset 1d ) > 30 # 告警的判定条件，参考Prometheus高级查询来设定
     for: 1m # 满足告警条件持续时间多久后，才会发送告警
     labels: #标签项
      team: node
     annotations: # 解析项，详细解释告警信息
      summary: "日活抖动超过30%"
      description: "日活抖动超过30%"
      value: "{{$value}}"
